name: Windows Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

    - name: Google Test
      working-directory: ${{github.workspace}}/build
      shell: bash
      # On windows ctest does not work.
      # run: GTEST_COLOR=1 ctest --verbose
      run: $BUILD_TYPE/aligned-allocator_test.exe
